Restore the ''import "unsafe'' removed in edf3b105aa6bf254e9c2b922e3bf2f79e5466123. This was causing build failures with tools dependent on Flatbuffers in Go. E.g. go/src/github.com/google/flatbuffers/go/sizes.go:50: undefined: unsafe in unsafe.Pointer